---
- hosts: all
  tasks:
    - name: Gather Facts
      ansible.builtin.setup:
      
    - name: Install Nginx package for Debian-based systems
      ansible.builtin.apt:
        name: nginx
        state: present
      when: ansible_os_family == "Debian"

    - name: Install Nginx package for RedHat-based systems
      ansible.builtin.yum:
        name: nginx
        state: present
      when: ansible_os_family == "RedHat"

    - name: Start and Enable Nginx service for Debian-based systems
      ansible.builtin.service:
        name: nginx
        state: started
        enabled: yes
      when: ansible_os_family == "Debian"
   
    - name: Start and Enable Nginx service for RedHat-based systems
      ansible.builtin.service:
        name: nginx
        state: started
        enabled: yes
      when: ansible_os_family == "RedHat"